CREATE DATABASE LICITANET;

CREATE TABLE LICITANET_COMPANY (
    id INT (11) NOT NULL AUTO_INCREMENT,

    uf VARCHAR (255) DEFAULT NULL,
    fantasy_name VARCHAR (255) DEFAULT NULL,
    cnpj VARCHAR (255) DEFAULT NULL,

    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) CHARSET = utf8;

CREATE TABLE LICITANET_PROVIDER (
    id INT (11) NOT NULL AUTO_INCREMENT,

    id_company VARCHAR (255) DEFAULT NULL,
    name VARCHAR (255) DEFAULT NULL,
    cpf_cnpj VARCHAR (255) DEFAULT NULL,
    telephone VARCHAR (255) DEFAULT NULL,
    idade VARCHAR (255) DEFAULT NULL,
    rg VARCHAR (255) DEFAULT NULL,
    birthdate VARCHAR (255) DEFAULT NULL,

    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) CHARSET = utf8;
